cas:
  #Required properties
  server-url-prefix: http://cas.example.org:8080/cas
  server-login-url: http://cas.example.org:8080/cas/login
  client-host-url: http://cas.client1.org:11001

  #Optional properties
  authentication-url-patterns: [/protected, /protected2, /protected3, /logout]
  validation-url-patterns: [/protected, /protected2, /protected3]
#  request-wrapper-url-patterns:
#  assertion-thread-local-url-patterns:
#  gateway:
#  use-session:
#  redirect-after-validation:
#  allowed-proxy-chains:
#  proxy-callback-url:
#  proxy-receptor-url:
#  accept-any-proxy:

casLogoutUrl: http://cas.example.org:8080/cas/logout?service=http://cas.example.org:8080/client1

spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

server:
  port: 11001
  servlet:
    context-path: /client1