#cas:
#  #Required properties
#  server-url-prefix: http://cas.example.org:8080/cas
#  server-login-url: http://cas.example.org:8080/cas/login
#  client-host-url: http://cas.client1.org:11001
#
#  #Optional properties
#  authentication-url-patterns: [/protected, /protected2]
#  validation-url-patterns: [/protected, /protected2]
#  #request-wrapper-url-patterns: [/protected, /protected2]
#  #assertion-thread-local-url-patterns: [/*]
#
#  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
#  #validation-type: SAML
#
#  #gateway: true
#  #use-session: false
#  #redirect-after-validation: false
#  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
#  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
#  #proxy-receptor-url: /proxy-callback
#  #accept-any-proxy: true
#
#casLogoutUrl: http://cas.example.org:8080/cas/logout?service=http://cas.client1.org:11001
cas:
  #Required properties
  server-url-prefix: http://192.168.80.130/cas
  server-login-url: http://192.168.80.130/cas/login
  client-host-url: http://192.168.80.130:80/client1

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
casLogoutUrl: http://192.168.80.130/cas/logout?service=http://192.168.80.130:80/client1

spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

server:
  port: 11001
  servlet:
    context-path: /client1