cas:
  #Required properties
  server-url-prefix: http://cas.example.org:8080/cas
  server-login-url: http://cas.example.org:8080/cas/login
  client-host-url: http://cas.client2.org:11002

  #Optional properties
  authentication-url-patterns: [/protected, /protected2, /logout]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  #validation-type: SAML

  #gateway: true
  #use-session: false
  #redirect-after-validation: false
  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: http://cas.example.org:8080/cas/logout?service=http://cas.client2.org:11002

spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

server:
  port: 11002